### ISSUE TITLE
bug: async_run raise `ValueError: filedescriptor out of range in select()`

### ISSUE THREAD

**Issue by schneesu** [Tencent/bk-bcs-saas#1520]
触发条件：执行一定时间后可能出现，重新 部署 / 调度 可暂时解决
```log
Traceback (most recent call last):
  File "/.../rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/.../backend/container_service/clusters/cc_host/views.py", line 49, in hosts
    host_list = utils.fetch_cc_app_hosts(username, bk_biz_id, params['set_id'], params['module_id'])
  File "/.../backend/container_service/clusters/cc_host/utils.py", line 34, in fetch_cc_app_hosts
    return cc.list_all_hosts_by_topo(username, bk_biz_id, bk_module_ids, bk_set_ids)
  File "/.../backend/components/cc.py", line 387, in list_all_hosts_by_topo
    results = async_run(tasks)
  File "/.../backend/utils/async_run.py", line 58, in async_run
    loop.run_until_complete(asyncio.wait(async_tasks))
  File "/.../asyncio/base_events.py", line 460, in run_until_complete
    self.run_forever()
  File "/.../asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/.../asyncio/base_events.py", line 1404, in _run_once
    event_list = self._selector.select(timeout)
  File "/.../selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "/.../gevent/monkey.py", line 509, in _select
    return select.select(*args, **kwargs)
  File "/.../gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
```

**Comment by schneesu** [comment]
1. gevent issue，没有具体解决
https://github.com/gevent/gevent/issues/1348

2. issue 中提及：gevent 1.2a1 调整部分规则，在这个版本之后，就会抛出 ValueError 异常
http://www.gevent.org/changelog_1_2.html#select-poll

3. 相同的错误，目前没有回答
https://stackoverflow.com/questions/65059246/filedescriptor-out-of-range-in-select-when-using-celery-with-django

4. 对 asyncio 该问题的一个讨论，有提及可能的解决办法
https://www.mail-archive.com/python-list@python.org/msg452501.html

![image](https://user-images.githubusercontent.com/37054728/133764259-f5bdad9d-a58e-4af7-9819-5c555d057d51.png)
看起来可能是 SelectSelector 有最大 fileno 的限制（一般是 1024），poll & epoll 则没有该限制
![image](https://user-images.githubusercontent.com/37054728/133764398-f818aed8-006e-43ca-ae47-dba54c152707.png)

5. 考虑到 linux 上没有 kqueue，mac 上没有 epoll，建议使用 `PollSelector`
- [Does OS X not support epoll function?](https://stackoverflow.com/questions/13856413/does-os-x-not-support-epoll-function)
- [Why doesn't linux implement kqueue?](https://www.reddit.com/r/linux/comments/1drwuw/why_doesnt_linux_implement_kqueue/)
- [kqueue & epoll 异同](
https://www.cnblogs.com/fg123/p/5256553.html)

6. asyncio 指定 selector 示例
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.SelectorEventLoop

**Comment by schneesu** [comment]
![image](https://user-images.githubusercontent.com/37054728/134276729-5280022d-4b79-444c-80e3-80bf42afa84c.png)

![image](https://user-images.githubusercontent.com/37054728/134276775-24d3d202-5a02-4860-b0f6-eba9d19834d0.png)

![image](https://user-images.githubusercontent.com/37054728/134276804-fff9415e-33e8-4b31-add9-9d687ca2e3db.png)

![image](https://user-images.githubusercontent.com/37054728/134276640-d3a42777-eccf-4ee2-aabe-60bda30b35c6.png)

![image](https://user-images.githubusercontent.com/37054728/134277013-efd7dddd-979a-4b5d-b994-9694b20a87f1.png)


asyncio 开放的方法基本是走 EventLoopPolicy，与 DefaultEventLoopPolicy，BaseSelectorEventLoop 是很强的绑定关系，指定难度较大，可能要重写部分的方法等

**Comment by schneesu** [comment]
有开发者提出 1.4.0- 版本的 gevent 中存在替换 DefaultSelector = SelectSelector 的问题，其实 PollSelector，gevent 项目成员表示在 1.5.0+ 版本中修复了该问题：https://github.com/gevent/gevent/issues/1466

![image](https://user-images.githubusercontent.com/37054728/134277414-7737eee3-219f-45e2-b4d1-953c0698424a.png)

![image](https://user-images.githubusercontent.com/37054728/134277450-c189dcbe-0e6c-40ad-ac05-80ef4647581a.png)

**Comment by schneesu** [comment]
同步结论，升级 gevent 版本到 1.5.0
