### ISSUE TITLE
npm run public运行报错

### ISSUE THREAD

**Issue by Jimgong826** [Tencent/bk-bcs-saas#490]
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new CopyPlugin (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/copy-webpack-plugin/dist/index.js:24:30)
    at module.exports (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/webpack.config.js:116:13)
    at handleFunction (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/workspace/src/bk-bcs-saas-master/bcs-projmgr/frontend/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devops-common@1.0.0 public: `npm run dll && webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devops-common@1.0.0 public script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-11T02_39_30_076Z-debug.log

**Comment by ielgnaw** [comment]
对 webpack 配置有修改吗？能发来看看吗？

**Comment by Jimgong826** [comment]
修改webpack，添加options已解决
